import Foundation

extension Notification.Name {
    static let interfaceLanguageChanged = Notification.Name("winexp.interfaceLanguageChanged")
}

/// Persisted identifiers never depend on the language used to display them.
enum InterfaceLanguage: String, CaseIterable {
    case system, english = "en", simplifiedChinese = "zh-Hans"

    var title: String {
        switch self {
        case .system: return L("Follow system language")
        case .english: return "English"
        case .simplifiedChinese: return "简体中文"
        }
    }
}

enum Localization {
    static var language: InterfaceLanguage {
        Settings.shared.language
    }

    static var isChinese: Bool {
        switch language {
        case .simplifiedChinese: return true
        case .english: return false
        case .system: return Locale.preferredLanguages.first?.hasPrefix("zh") == true
        }
    }

    static var locale: Locale { Locale(identifier: isChinese ? "zh_CN" : "en_US") }

    static func string(_ key: String) -> String {
        isChinese ? (chinese[key] ?? key) : key
    }

    static let chinese: [String: String] = [
        "Eject": "弹出",
        "Could not eject “{0}”.\n{1}": "无法弹出“{0}”。\n{1}",
        "Window button position": "窗口按钮位置",
        "This macOS version does not allow changing the default folder app through this interface. Finder remains the default; external open and reveal still work.": "当前 macOS 无法通过此接口更改默认目录管理器。Finder 仍为默认；外部打开和文件定位功能可正常使用。",
        "Integration": "系统集成",
        "Only local file paths and file-explorer links are supported.": "仅支持本机文件路径和 file-explorer 链接。",
        "The link must contain an absolute path.": "链接须包含完整的本机路径。",
        "The path does not exist or cannot be accessed: {0}": "路径不存在或无法访问：{0}",
        "Unknown": "未知",
        "Finder could not be found.": "未找到 Finder。",
        "The system could not change the default folder app: {0}": "系统未能更改默认目录管理器：{0}",
        "The system has not applied the folder association. Refresh the status and try again.": "系统尚未应用目录关联，请刷新状态后重试。",
        "Default folder app": "默认目录管理器",
        "This app opens ordinary folders by default.": "普通文件夹默认由本工具打开。",
        "The current system association for ordinary folders.": "当前系统中普通文件夹的打开方式。",
        "Applying…": "正在设置…",
        "Set as default": "设为默认",
        "Restore Finder": "恢复 Finder",
        "Folder association updated.": "目录关联已更新。",
        "Only folder opening is changed. Documents and apps keep their existing associations. macOS may ask you to confirm the change.": "仅更改文件夹的打开方式。文档和应用保持原有的打开方式。macOS 可能要求确认此更改。",
        "External open and reveal": "外部打开与文件定位",
        "Other apps can pass a folder to open it, or a file to select it in its folder. Multiple files in the same folder share one tab.": "其他程序可传入目录进行打开，或传入文件以定位并选中。同一目录中的多个文件会显示在同一标签页。",
        "Apps that explicitly call Finder may still open Finder. This setting cannot replace the system Open and Save dialogs.": "明确调用 Finder 的程序仍可能打开 Finder。本设置不会替换系统的打开和保存对话框。",

        "Alternating row backgrounds": "交替行背景",
        "Subtle alternating colours in Details view": "在详细信息列表中使用轻微的交替底色",

        "Move": "移动",
        "Archive": "压缩文件",
        "%.1f hours": "%.1f 小时",
        "About implementation": "使用 Swift、AppKit 和 SwiftUI 编写。Fluent 图标按照 Windows 的 16pt 网格重新绘制为矢量图形，因为 macOS 不提供 Segoe Fluent Icons 字体。采用 Apache 2.0 许可证，可自由再分发，但须保留作者署名。本应用与 Microsoft 无关联。",

        " bytes": " 字节",
        "Size: ": "大小：",
        "Commands run in zsh with your selection in the environment: ": "命令通过 zsh 执行，所选项目由以下环境变量提供：",

        "{0}, {1} tab{2}": "{0}，{1} 个标签页",
        "{0} File": "{0} 文件",
        "{0} bytes": "{0} 字节",
        "{0} only left · {1} only right · {2} differ": "仅左侧 {0} 项 · 仅右侧 {1} 项 · 不同 {2} 项",
        "Running {0}": "正在运行 {0}",
        "Could not run “{0}”.\n{1}": "无法运行“{0}”。\n{1}",
        "“{0}” exited with status {1}.": "“{0}”已退出，状态码为 {1}。",
        "{0} finished": "{0} 已完成",
        "Could not extract “{0}” from the archive.": "无法从压缩文件中提取“{0}”。",
        "Extracting {0}": "正在解压 {0}",
        "Could not extract the archive.\n{0}": "无法解压文件。\n{0}",
        "Extracted to {0}": "已解压到 {0}",
        "{0} item{1} copied": "已复制 {0} 个项目",
        "{0} item{1} cut": "已剪切 {0} 个项目",
        "Renamed {0} item{1}": "已重命名 {0} 个项目",
        "Undo {0}": "撤销{0}",
        "{0} item{1}": "{0} 个项目",
        "{0} item{1} selected{2}": "已选择 {0} 个项目{2}",
        "Windows can't find '{0}'. Check the spelling and try again.": "找不到“{0}”。请检查路径后重试。",
        "Rename {0} items": "重命名 {0} 个项目",
        "{0} name{1} would clash": "{0} 个名称存在冲突",
        "Start at {0}": "起始编号 {0}",
        "{0} digits": "{0} 位数字",
        "{0} of {1} will change": "共 {1} 项，将更改 {0} 项",
        "Could not rename “{0}”. {1}": "无法重命名“{0}”。{1}",
        "Finished, {0} item{1}": "已完成，共 {0} 个项目",
        "{0} to {1}": "{0}到 {1}",
        "{0} items selected": "已选择 {0} 个项目",
        "{0} was used by “{1}”, so it has been reassigned.": "{0} 原用于“{1}”，现已重新分配。",
        "Version {0}": "版本 {0}",
        "Change icon: {0}": "更改图标：{0}",
        "{0} Properties": "{0} 属性",
        "{0} items": "{0} 个项目",
        "{0} Files, {1} Folders": "{0} 个文件，{1} 个文件夹",
        "{0}\n{1}\nDate modified: {2}": "{0}\n{1}\n修改日期：{2}",
        "Are you sure you want to permanently delete these {0} items?": "确定要永久删除这 {0} 个项目吗？",
        "Are you sure you want to move these {0} items to the Recycle Bin?": "确定要将这 {0} 个项目移至回收站吗？",
        "{0} of {1}": "{0} / {1}",
        "{0}/s, {1} left": "{0}/秒，剩余 {1}",
        "{0} seconds": "{0} 秒",
        "{0} minutes": "{0} 分钟",
        "{0} {1} sets of items": "{0} {1} 组项目",
        "{0} {1} of {2} items": "{0}，{1} / {2} 个项目",
        "Error: {0}": "错误：{0}",
        "Up to {0} (Alt+Up)": "返回上级 {0} (Alt+Up)",
        "Search {0}": "搜索 {0}",
        "Cut ({0})": "剪切 ({0})",
        "Copy ({0})": "复制 ({0})",
        "Paste ({0})": "粘贴 ({0})",
        "Rename ({0})": "重命名 ({0})",
        "Delete ({0})": "删除 ({0})",
        "Details pane ({0})": "详细信息窗格 ({0})",
        "Dual pane ({0})": "双栏视图 ({0})",
        "Open {0}": "打开 {0}",
        "Rename {0} items…": "重命名 {0} 个项目…",
        "Home": "主页",
        "Gallery": "图库",
        "This PC": "此电脑",
        "Network": "网络",
        "Recycle Bin": "回收站",
        "Desktop": "桌面",
        "Desktop folder": "桌面文件夹",
        "Downloads": "下载",
        "Documents": "文档",
        "Pictures": "图片",
        "Music": "音乐",
        "Videos": "视频",
        "Local Disk (C:)": "本地磁盘 (C:)",
        "File Explorer": "文件资源管理器",
        "File Explorer Settings": "文件资源管理器设置",
        "About File Explorer": "关于文件资源管理器",
        "Hide File Explorer": "隐藏文件资源管理器",
        "Quit File Explorer": "退出文件资源管理器",
        "Edit": "编辑",
        "Window": "窗口",
        "Minimize": "最小化",
        "Zoom": "缩放",
        "Copy": "复制",
        "Cut": "剪切",
        "Paste": "粘贴",
        "Paste shortcut": "粘贴快捷方式",
        "Copy as path": "复制为路径",
        "Copy path": "复制路径",
        "Undo": "撤销",
        "Redo": "重做",
        "Select all": "全选",
        "Select All": "全选",
        "Select none": "取消选择",
        "Invert selection": "反向选择",
        "Rename": "重命名",
        "Delete": "删除",
        "Delete File": "删除文件",
        "Delete (Recycle Bin)": "删除（移至回收站）",
        "Delete permanently": "永久删除",
        "New": "新建",
        "New item": "新建项目",
        "New folder": "新建文件夹",
        "New text document": "新建文本文档",
        "Compress to ZIP": "压缩为 ZIP",
        "Compress to ZIP file": "压缩为 ZIP 文件",
        "Create shortcut": "创建快捷方式",
        "New tab": "新建标签页",
        "Close tab": "关闭标签页",
        "Next tab": "下一个标签页",
        "Previous tab": "上一个标签页",
        "New window": "新建窗口",
        "Go to Home": "转到主页",
        "Go to Desktop folder": "转到桌面文件夹",
        "Show desktop (hide all windows)": "显示桌面（隐藏所有窗口）",
        "Show desktop": "显示桌面",
        "Dual pane": "双栏视图",
        "Switch pane": "切换窗格",
        "Swap panes": "交换窗格",
        "Copy to the other pane": "复制到另一窗格",
        "Move to the other pane": "移动到另一窗格",
        "Rename many items": "批量重命名",
        "Compare and sync folders": "比较与同步文件夹",
        "Connect to server": "连接服务器",
        "Workspaces": "工作区",
        "Shelf": "暂存架",
        "Extract archive": "解压文件",
        "Go to Downloads": "转到下载",
        "Go to Documents": "转到文档",
        "Go to Pictures": "转到图片",
        "Go to Music": "转到音乐",
        "Go to Videos": "转到视频",
        "Go to This PC": "转到此电脑",
        "Refresh": "刷新",
        "Back": "后退",
        "Forward": "前进",
        "Up one level": "上一级",
        "Focus address bar": "定位地址栏",
        "Focus search": "定位搜索框",
        "Properties": "属性",
        "Open in Terminal": "在终端中打开",
        "Show in Finder": "在访达中显示",
        "Show hidden items": "显示隐藏项目",
        "Show file name extensions": "显示文件扩展名",
        "Navigation pane": "导航窗格",
        "Details pane": "详细信息窗格",
        "Preview pane": "预览窗格",
        "Full screen": "全屏",
        "Settings": "设置",
        "Extra large icons": "超大图标",
        "Large icons": "大图标",
        "Medium icons": "中等图标",
        "Small icons": "小图标",
        "List": "列表",
        "Details": "详细信息",
        "Tiles": "平铺",
        "Content": "内容",
        "Clipboard": "剪贴板",
        "Selection": "选择",
        "Files": "文件",
        "Folders": "文件夹",
        "Folder": "文件夹",
        "Tabs & windows": "标签页与窗口",
        "Navigation": "导航",
        "View": "查看",
        "Use system setting": "跟随系统",
        "Light": "浅色",
        "Dark": "深色",
        "Windows blue": "Windows 蓝",
        "Teal": "青色",
        "Green": "绿色",
        "Orange": "橙色",
        "Red": "红色",
        "Pink": "粉色",
        "Purple": "紫色",
        "Graphite": "石墨灰",
        "Name": "名称",
        "Date modified": "修改日期",
        "Type": "类型",
        "Size": "大小",
        "Date created": "创建日期",
        "Quick access": "快速访问",
        "Recent": "最近使用",
        "Favorites": "收藏",
        "Shared": "共享",
        "Stored locally": "存储在本机",
        "Date accessed": "访问日期",
        "Account": "账户",
        "Activity": "活动",
        "No shared files.": "暂无共享文件。",
        "No recent files.": "暂无最近使用的文件。打开文件后会显示在这里。",
        "Open": "打开",
        "Open file location": "打开文件所在位置",
        "Open in new tab": "在新标签页中打开",
        "Open in new window": "在新窗口中打开",
        "Open with": "打开方式",
        "Unpin from Quick access": "从快速访问中取消固定",
        "Pin to Quick access": "固定到快速访问",
        "Change icon…": "更改图标…",
        "Extract here": "解压到此处",
        "Add to shelf": "添加到暂存架",
        "Sort by": "排序方式",
        "Ascending": "升序",
        "Descending": "降序",
        "No apps available": "没有可用的应用",
        "Share": "共享",
        "Extract": "解压",
        "Sort": "排序",
        "Filter": "筛选",
        "See more": "更多选项",
        "Cloud storage status": "云存储状态",
        "Group by": "分组依据",
        "Compact view": "紧凑视图",
        "Show": "显示",
        "Item check boxes": "项目复选框",
        "File name extensions": "文件扩展名",
        "Hidden items": "隐藏项目",
        "All": "全部",
        "Images": "图像",
        "Audio": "音频",
        "Archives": "压缩文件",
        "Applications": "应用程序",
        "Panes": "窗格",
        "Tools": "工具",
        "Go to": "转到",
        "Account disconnected": "未连接账户",
        "Cloud storage": "云存储",
        "No cloud account is connected.": "尚未连接云存储账户。",
        "Windows shows your Microsoft account here.": "此处显示云存储账户信息。",
        "Everything works on your local files.": "你仍可正常管理本机文件。",
        "Pin a folder to Quick access…": "将文件夹固定到快速访问…",
        "Hide this button": "隐藏此按钮",
        "Pin": "固定",
        "Path": "路径",
        "Click to type the path (Ctrl+L)": "点击输入路径 (Ctrl+L)",
        "New tab (Ctrl+T)": "新建标签页 (Ctrl+T)",
        "Close tab (Ctrl+W)": "关闭标签页 (Ctrl+W)",
        "Back (Alt+Left)": "后退 (Alt+Left)",
        "Forward (Alt+Right)": "前进 (Alt+Right)",
        "Refresh (F5)": "刷新 (F5)",
        "No items match your search.": "没有符合搜索条件的项目。",
        "This folder is empty.": "此文件夹为空。",
        "Appearance": "外观",
        "Shortcuts": "快捷键",
        "Folder icons": "文件夹图标",
        "Commands": "自定义命令",
        "About": "关于",
        "Done": "完成",
        "Theme": "主题",
        "Accent colour": "强调色",
        "Layout": "布局",
        "Tighter row spacing in Details view": "缩小详细信息视图中的行距",
        "Click a shortcut, then press the keys you want.": "点击快捷键，然后按下要设置的按键组合。",
        "Restore defaults": "恢复默认设置",
        "Also: ": "其他快捷键：",
        "Press a key…": "请按下按键…",
        "None": "无",
        "(None)": "（无）",
        "Restore default": "恢复默认值",
        "Pinned folders": "已固定的文件夹",
        "Add folder…": "添加文件夹…",
        "Unpin": "取消固定",
        "Unpinned": "未固定",
        "Pin again": "重新固定",
        "Right-click any folder and choose “Change icon” to customise it.": "右键点击文件夹，选择“更改图标”即可自定义。",
        "No customised folders yet.": "尚未自定义文件夹图标。",
        "Reset to the default folder icon": "恢复默认文件夹图标",
        "The Windows 11 File Explorer, rebuilt natively for macOS.": "为 macOS 原生打造的 Windows 11 风格文件资源管理器。",
        "Created by Alex Degryse": "作者：Alex Degryse",
        "Connect on LinkedIn": "访问 LinkedIn",
        "Source code": "源代码",
        "Colophon": "制作说明",
        "Icon": "图标",
        "Colour": "颜色",
        "No tint": "不着色",
        "Reset": "重置",
        "OK": "确定",
        "Cancel": "取消",
        "General": "常规",
        "Type of file:": "文件类型：",
        "Location:": "位置：",
        "Size:": "大小：",
        "Contains:": "包含：",
        "Created:": "创建时间：",
        "Modified:": "修改时间：",
        "Attributes:": "属性：",
        "Name:": "名称：",
        "Item type:": "项目类型：",
        "Folder path:": "文件夹路径：",
        "Full path:": "完整路径：",
        "Date modified:": "修改日期：",
        "Date created:": "创建日期：",
        "Owner:": "所有者：",
        "Hidden": "隐藏",
        "Read-only": "只读",
        "Shortcut": "快捷方式",
        "Yes": "是",
        "No": "否",
        "Are you sure you want to permanently delete this file?": "确定要永久删除此文件吗？",
        "Are you sure you want to move this file to the Recycle Bin?": "确定要将此文件移至回收站吗？",
        "Show file transfers": "显示文件传输",
        "Details view (Ctrl+Shift+6)": "详细信息视图 (Ctrl+Shift+6)",
        "Large icons view (Ctrl+Shift+2)": "大图标视图 (Ctrl+Shift+2)",
        "File transfers": "文件传输",
        "Clear finished": "清除已完成任务",
        "Nothing is being copied or moved.": "当前没有复制或移动任务。",
        "Waiting": "等待中",
        "Cancelled": "已取消",
        "Select a file to see its details.": "选择文件以查看详细信息。",
        "Total size": "总大小",
        "Location": "位置",
        "Attributes": "属性",
        "No preview available": "无法预览此文件",
        "Select a file to preview.": "选择文件以预览。",
        "Empty the shelf": "清空暂存架",
        "Hide the shelf": "隐藏暂存架",
        "Drop files here to hold on to them.": "将文件拖到这里暂存。",
        "Copy everything on the shelf into this folder": "将暂存架中的所有文件复制到此文件夹",
        "Copy here": "复制到此处",
        "Move everything on the shelf into this folder": "将暂存架中的所有文件移动到此文件夹",
        "Move here": "移动到此处",
        "A workspace remembers the tabs open in each pane, the split, and the view mode.": "工作区会保存各窗格的标签页、分栏比例和视图模式。",
        "Name this workspace": "工作区名称",
        "Save": "保存",
        "Nothing saved yet.": "尚未保存工作区。",
        "two panes": "双栏",
        "one pane": "单栏",
        "Only on the left": "仅左侧存在",
        "Only on the right": "仅右侧存在",
        "Different": "内容不同",
        "Identical": "相同",
        "Copy right": "复制到右侧",
        "Copy left": "复制到左侧",
        "Close": "关闭",
        "Left": "左侧",
        "Right": "右侧",
        "Comparing…": "比较中…",
        "Compare": "比较",
        "Differences only": "仅显示差异",
        "Pick two folders and compare them.": "选择两个文件夹进行比较。",
        "The folders match.": "两个文件夹内容相同。",
        "Both folders are empty.": "两个文件夹均为空。",
        "Choose a folder": "选择文件夹",
        "Choose": "选择",
        "Browse": "浏览",
        "A selected item": "选中的项目",
        "Selected files": "选中的文件",
        "Selected folders": "选中的文件夹",
        "The current folder": "当前文件夹",
        "New command": "新建命令",
        "Show commands.json": "显示 commands.json",
        "Applies to": "适用范围",
        "Script": "脚本",
        "Refresh the folder afterwards": "执行后刷新文件夹",
        "Unchanged": "保持不变",
        "lowercase": "全部小写",
        "UPPERCASE": "全部大写",
        "Title Case": "首字母大写",
        "Find": "查找",
        "Replace with": "替换为",
        "Match case": "区分大小写",
        "Prefix": "前缀",
        "Suffix": "后缀",
        "New extension": "新扩展名",
        "Number them": "添加编号",
        "Preview": "预览",
        "Address": "地址",
        "SMB, AFP, NFS, FTP and WebDAV. macOS handles the sign-in, so no password is typed into File Explorer.": "支持 SMB、AFP、NFS、FTP 和 WebDAV。登录由 macOS 处理，无需在本应用中输入密码。",
        "Recent servers": "最近连接的服务器",
        "Forget": "移除记录",
        "Connecting…": "连接中…",
        "Connect": "连接",
        "Waiting for macOS to mount the share.": "正在等待 macOS 挂载共享位置。",
        "No new volume appeared. If the sign-in window is still open, finish it and the share will show up under Network.": "未发现新挂载的卷。如果登录窗口仍打开，请完成登录，共享位置将显示在“网络”下。",
        "Path copied": "已复制路径",
        "The file name you specified is not valid or too long.": "文件名无效或过长。",
        "File folder": "文件夹",
        "File": "文件",
        "Text Document": "文本文档",
        "Adobe Acrobat Document": "PDF 文档",
        "Microsoft Word 97-2003 Document": "Microsoft Word 97-2003 文档",
        "Microsoft Word Document": "Microsoft Word 文档",
        "Microsoft Excel 97-2003 Worksheet": "Microsoft Excel 97-2003 工作表",
        "Microsoft Excel Worksheet": "Microsoft Excel 工作表",
        "Microsoft PowerPoint 97-2003 Presentation": "Microsoft PowerPoint 97-2003 演示文稿",
        "Microsoft PowerPoint Presentation": "Microsoft PowerPoint 演示文稿",
        "Compressed (zipped) Folder": "压缩文件夹",
        "Application": "应用程序",
        "Windows Installer Package": "Windows 安装程序包",
        "Application extension": "应用程序扩展",
        "Internet Shortcut": "互联网快捷方式",
        "HTML Document": "HTML 文档",
        "XML Document": "XML 文档",
        "JSON File": "JSON 文件",
        "MP3 Audio File": "MP3 音频文件",
        "Wave Sound": "WAV 音频文件",
        "MP4 Video File": "MP4 视频文件",
        "QuickTime Movie": "QuickTime 视频",
        "AVI Video File": "AVI 视频文件",
        "PNG File": "PNG 图像",
        "JPG File": "JPG 图像",
        "JPEG File": "JPEG 图像",
        "GIF File": "GIF 图像",
        "HEIC File": "HEIC 图像",
        "SVG Document": "SVG 图像",
        "Rich Text Document": "富文本文档",
        "Disk Image": "磁盘映像",
        "Disc Image File": "光盘映像文件",
        "TrueType Font File": "TrueType 字体文件",
        "OpenType Font File": "OpenType 字体文件",
        "Markdown Source File": "Markdown 源文件",
        "Microsoft Excel Comma Separated Values File": "CSV 表格文件",
        "Python Source File": "Python 源文件",
        "JavaScript File": "JavaScript 文件",
        "Swift Source File": "Swift 源文件",
        "Shell Script": "Shell 脚本",
        "Windows Batch File": "Windows 批处理文件",
        "Windows PowerShell Script": "Windows PowerShell 脚本",
        "Copying": "正在复制",
        "Moving": "正在移动",
        "Deleting": "正在删除",
        "Language": "界面语言",
        "Follow system language": "跟随系统语言",
        "Language changes take effect immediately.": "切换后立即生效。",
        "Comfortable spacing with Compact view off": "关闭紧凑视图后，使用更舒适的行距",
    ]
}

/// Explicitly localize interface labels; never run user filenames through this function.
func L(_ key: String) -> String { Localization.string(key) }

/// Positional placeholders keep filenames and paths intact, including percent characters.
func LF(_ key: String, _ arguments: Any...) -> String {
    var text = L(key)
    let pattern = try! NSRegularExpression(pattern: "\\{([0-9]+)\\}")
    let matches = pattern.matches(in: text, range: NSRange(text.startIndex..., in: text))
    for match in matches.reversed() {
        guard let indexRange = Range(match.range(at: 1), in: text),
              let index = Int(text[indexRange]), index < arguments.count,
              let range = Range(match.range, in: text) else { continue }
        text.replaceSubrange(range, with: String(describing: arguments[index]))
    }
    return text
}
